# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version ">= 1.7.2"

Dotenv.load

ENV['VAGRANT_DEFAULT_PROVIDER'] = "aws"

Vagrant.configure(2) do |config|

  config.vm.box = "dummy"
  # config.vm.boot_timeout = 30


  # Disabling the default /vagrant share
  #   http://docs.vagrantup.com/v2/synced-folders/basic_usage.html
  config.vm.synced_folder ".", "/vagrant", disabled: true

  #config.vm.synced_folder "./sync_dir", "/vagrant_rsync", disabled: true
  #config.vm.synced_folder "./data", "/vagrant_data"



# Amazon Linux

  [
#    "user-proxy-01",
    "system-proxy-01"
  ].each do |config_name|

    config.vm.communicator = "ssh"

    config.vm.define config_name do |node|

      node.vm.provider :aws do |aws, override|

        aws.access_key_id     = ENV['AWS_ACCESS_KEY_ID']
        aws.secret_access_key = ENV['AWS_SECRET_ACCESS_KEY']
        aws.keypair_name      = ENV['AWS_KEY_PAIR_NAME']
 
        aws.region            = ENV['AWS_REGION']
        aws.availability_zone = ENV['AWS_AVAILABILITY_ZONE']

        aws.subnet_id         = ENV['AWS_SUBNET_ID']
        aws.security_groups   = ENV['AWS_SECURITY_GROUPS'].split(',')
#        aws.subnet_id         = "subnet-f3e601aa"
#        aws.security_groups   = "sg-1e25fe7b"

        aws.ami               = ENV['AWS_IMAGE_ID']
        aws.instance_type     = ENV['AWS_INSTANCE_TYPE']
#        aws.ami               = "ami-25436924"
#        aws.instance_type     = "t1.micro"

        aws.tags = {
          'Name' => config_name
        }

        aws.user_data = File.read("user_data.txt")

        override.ssh.username = ENV['SSH_USER_NAME']
        override.ssh.private_key_path = ENV['AWS_PRIVATE_KEY_PATH']
#        override.ssh.username = "root"
#        override.ssh.private_key_path = "~/.ssh/fkuvagrantTokyo.pem"
#        override.ssh.pty = true

      end

    end

  end

end


